from datetime import date


EMISSION_BURN_HOTKEY = "5GU4Xkd3dCGTU3s8VLcHGc5wsD5M8XyxDca5yDQhYm1mVXFu"

# General miner pool sizes
MIN_IDEAL_NUM_MINERS_IN_POOL = 8

# Evaluation retry limits
MAX_EVAL_ATTEMPTS = 4
MAX_TOURNAMENT_EVAL_ATTEMPTS = 3

# Task scoring
SCORE_PENALTY = -1
FIRST_PLACE_SCORE = 3

# PvP and individual environment scoring
INDIVIDUAL_WIN_MARGIN = 0.015
PVP_ENV_WIN_POINTS = 3
PVP_ENV_DRAW_POINTS = 1
PVP_ENV_LOSS_POINTS = 0
PVP_WIN_PCT_THRESHOLD = 0.60
PVP_PERF_DIFF_SLOPE = 0.125

# Tournament score and weight distribution
TOURNAMENT_PARTICIPATION_WEIGHT = 0.0001
TOURNAMENT_PAID_RANKS = 2
TOURNAMENT_SIMPLE_DECAY_BASE = 0.25
MAX_TEXT_TOURNAMENT_WEIGHT = 0.48
MAX_IMAGE_TOURNAMENT_WEIGHT = 0.32
MAX_ENVIRONMENT_TOURNAMENT_WEIGHT = 0.175
TOURNAMENT_TEXT_WEIGHT = 0.40
TOURNAMENT_IMAGE_WEIGHT = 0.175
TOURNAMENT_ENVIRONMENT_WEIGHT = 0.175

# Burn and emission weight dynamics
BURN_REDUCTION_RATE = 5.0
MAX_BURN_REDUCTION = 0.8
EMISSION_MULTIPLIER_THRESHOLD = 0.10
EMISSION_MULTIPLIER_RATE = 2.0
EMISSION_BOOST_DECAY_PER_WIN = 0.01
# Champion emission decays on a piecewise-linear *retention* curve (multiplier on
# the champion's full day-0 emission weight = base + boost). Fast early drop, a
# plateau, then a cliff to zero at 40 days. (days_since_reign_start, retention).
EMISSION_TIME_DECAY_CURVE: tuple[tuple[float, float], ...] = (
    (0.0, 1.00),
    (7.0, 0.50),
    (30.0, 0.30),
    (40.0, 0.00),
)
EMISSION_TIME_DECAY_START_DATE = date(2025, 11, 26)
SECONDS_PER_DAY = 86400.0

ALPHA_PER_SECOND = 1.0 / 12.0
MINER_ALPHA_SHARE = 0.41
DAILY_ALPHA_TO_MINERS = ALPHA_PER_SECOND * SECONDS_PER_DAY * MINER_ALPHA_SHARE
